### ISSUE TITLE
Use it with CtrlP

### ISSUE THREAD

**Issue by pablopunk** [camspiers/animate.vim#2]
Hi! Do you have any clue about how to use this plugin with [CtrlP](https://github.com/ctrlpvim/ctrlp.vim) ? Looks dope!

**Comment by camspiers** [comment]
The following should do it:

```
let g:ctrlp_buffer_func = {
  \ 'enter': 'OpenCtrlP',
  \ }

function! OpenCtrlP() abort
  wincmd J
  resize 1
  call animate#window_percent_height(0.3)
endfunction
```

You can adjust the height percentage as you need.

**Comment by camspiers** [comment]
For clarity:

`wincmd J` <- sends the window to the bottom

`resize 1` <- starts the size small

`call animate#window_percent_height(0.3)` resizes to 30% height.

**Comment by pablopunk** [comment]
Great! Thanks
