### ISSUE TITLE
Invalid in command-line window .... noautocmd windo if ! &winfixwidth | let nowinfixwidths[winnr()] = 1 | set winfixwidth | endif

### ISSUE THREAD

**Issue by 3coma3** [camspiers/animate.vim#4]
Hi, when I open the history editing with `q:` I receive this message:

> Invalid in command-line window; <CR> executes, CTRL-C quits: 
> noautocmd windo if ! &winfixwidth | let nowinfixwidths[winnr()] = 1 | set winfixwidth | endif

I've just grepped the string on all my vim configuration and found it on:
`plugins/animate.vim/plugin/animate.vim:109:        noautocmd windo if ! &winfixwidth | let nowinfixwidths[winnr()] = 1 | set winfixwidth | endif
`

Is this something easily solvable, can others reproduce?

**Comment by 3coma3** [comment]
Added a PR, seems it's simple enough to fix (tested it and the errors disappear)
#5

**Comment by camspiers** [comment]
Thanks!
